package com.dragon.entity;

// Generated 2015-6-4 14:41:35 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TSysDict generated by hbm2java
 */
@Entity
@Table(name = "t_sys_dict", catalog = "dragon")
public class SysDict implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String dictCode;
	private String dictName;
	private String itemCode;
	private String parentItemId;
	private String itemValue;
	private String itemStatusCode;
	private String displaySeq;
	private String createTime;
	private String updateTime;

	public SysDict() {
	}

	public SysDict(String dictCode, String dictName, String itemCode,
			String parentItemId, String itemValue, String itemStatusCode,
			String displaySeq, String createTime, String updateTime) {
		this.dictCode = dictCode;
		this.dictName = dictName;
		this.itemCode = itemCode;
		this.parentItemId = parentItemId;
		this.itemValue = itemValue;
		this.itemStatusCode = itemStatusCode;
		this.displaySeq = displaySeq;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "dict_code", length = 45)
	public String getDictCode() {
		return this.dictCode;
	}

	public void setDictCode(String dictCode) {
		this.dictCode = dictCode;
	}

	@Column(name = "dict_name", length = 45)
	public String getDictName() {
		return this.dictName;
	}

	public void setDictName(String dictName) {
		this.dictName = dictName;
	}

	@Column(name = "item_code", length = 45)
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	@Column(name = "parent_item_id", length = 45)
	public String getParentItemId() {
		return this.parentItemId;
	}

	public void setParentItemId(String parentItemId) {
		this.parentItemId = parentItemId;
	}

	@Column(name = "item_value", length = 45)
	public String getItemValue() {
		return this.itemValue;
	}

	public void setItemValue(String itemValue) {
		this.itemValue = itemValue;
	}

	@Column(name = "item_status_code", length = 45)
	public String getItemStatusCode() {
		return this.itemStatusCode;
	}

	public void setItemStatusCode(String itemStatusCode) {
		this.itemStatusCode = itemStatusCode;
	}

	@Column(name = "display_seq", length = 45)
	public String getDisplaySeq() {
		return this.displaySeq;
	}

	public void setDisplaySeq(String displaySeq) {
		this.displaySeq = displaySeq;
	}

	@Column(name = "create_time", length = 45)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	@Column(name = "update_time", length = 45)
	public String getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

}
