package com.dragon.entity;

// Generated 2015-6-4 14:41:35 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TSysFunc generated by hbm2java
 */
@Entity
@Table(name = "t_sys_func", catalog = "dragon")
public class SysFunc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String funcName;
	private String funcType;
	private String funcAction;
	private String funcDesc;
	private Integer parentId;
	private Integer displaySequence;
	private String statusCode;

	public SysFunc() {
	}

	public SysFunc(String funcName, String funcType, String funcAction,
			String funcDesc, Integer parentId, Integer displaySequence) {
		this.funcName = funcName;
		this.funcType = funcType;
		this.funcAction = funcAction;
		this.funcDesc = funcDesc;
		this.parentId = parentId;
		this.displaySequence = displaySequence;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "func_name", length = 45)
	public String getFuncName() {
		return this.funcName;
	}

	public void setFuncName(String funcName) {
		this.funcName = funcName;
	}

	@Column(name = "func_type", length = 45)
	public String getFuncType() {
		return this.funcType;
	}

	public void setFuncType(String funcType) {
		this.funcType = funcType;
	}

	@Column(name = "func_action", length = 45)
	public String getFuncAction() {
		return this.funcAction;
	}

	public void setFuncAction(String funcAction) {
		this.funcAction = funcAction;
	}

	@Column(name = "func_desc", length = 45)
	public String getFuncDesc() {
		return this.funcDesc;
	}

	public void setFuncDesc(String funcDesc) {
		this.funcDesc = funcDesc;
	}

	@Column(name = "display_sequence")
	public Integer getDisplaySequence() {
		return this.displaySequence;
	}
	
	public void setDisplaySequence(Integer displaySequence) {
		this.displaySequence = displaySequence;
	}
	
	@Column(name = "parent_id")
	public Integer getParentId() {
		return parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "status_code", length = 45)
	public String getStatusCode() {
		return statusCode;
	}

	public void setStatusCode(String statusCode) {
		this.statusCode = statusCode;
	}
	
	
}
