package com.dragon.entity;

// Generated 2015-6-4 14:41:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TUserDetails generated by hbm2java
 */
@Entity
@Table(name = "t_user_details", catalog = "dragon")
public class UserDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer userId;
	private Integer hometownId;
	private Integer locationId;
	private Integer universityId;
	private Integer departmentId;
	private Date birthday;
	private String education;
	private String qq;
	private String TUserDetailscol;

	public UserDetails() {
	}

	public UserDetails(Integer userId, Integer hometownId, Integer locationId,
			Integer universityId, Integer departmentId, Date birthday,
			String education, String qq, String TUserDetailscol) {
		this.userId = userId;
		this.hometownId = hometownId;
		this.locationId = locationId;
		this.universityId = universityId;
		this.departmentId = departmentId;
		this.birthday = birthday;
		this.education = education;
		this.qq = qq;
		this.TUserDetailscol = TUserDetailscol;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "hometown_id")
	public Integer getHometownId() {
		return this.hometownId;
	}

	public void setHometownId(Integer hometownId) {
		this.hometownId = hometownId;
	}

	@Column(name = "location_id")
	public Integer getLocationId() {
		return this.locationId;
	}

	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	@Column(name = "university_id")
	public Integer getUniversityId() {
		return this.universityId;
	}

	public void setUniversityId(Integer universityId) {
		this.universityId = universityId;
	}

	@Column(name = "department_id")
	public Integer getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "education", length = 45)
	public String getEducation() {
		return this.education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	@Column(name = "qq", length = 45)
	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	@Column(name = "t_user_detailscol", length = 45)
	public String getTUserDetailscol() {
		return this.TUserDetailscol;
	}

	public void setTUserDetailscol(String TUserDetailscol) {
		this.TUserDetailscol = TUserDetailscol;
	}

}
